# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5939f48b009a18c61bc3a0b84e20fa51dc176252d456372bdd9e3ffc654567dec510f025c996ec1e67a49a962e756d2c071018de1636fabb35ed9f706828b74

test:
  secret_key_base: b479ff67714c6aaf270d50334ede337c9ebeba0f72f2e5e742a6e67e21e66faa3c7e58abbfb04ff67e41ec7bbbec49e40be84f7529dccedd4dded69de0afc84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
